apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
spec:
  project: default
  source:
    repoURL: https://github.com/JoostVermeij/test-openshift.git
    targetRevision: HEAD
    path: test
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
